language: r
sudo: false
cache: packages
r_packages:
- covr
- drat
after_success:
- Rscript -e 'library("covr");codecov()'
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  drat.sh
env:
  global:
    secure: U6yY2llcPE6QVi08Zbb3hIK+9eMDAvBdbakZA51UBlqgz8JMzZAfDjdOvPYxOmokMuyxoBcFYHpuqsGYoVlsMn4RoYYvcoDFtWxsdVJDX5rxfp7Mv5Kp5U9PM8Q/Fpn5fmX5CjdxHYEuZ0c+blJMtOms1jcq7TmUYZ16YIbnaA4=
